name: MyCircle Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  pull_code:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}} # key generated on the server
          host: ${{secrets.HOST_PROD}}
          username: ${{secrets.USERNAME}}
          # || true needed because pm2 delete returns 1 when no process is running
          script_stop: true
          script: |
            cd /var/www/html/mycircle
            eval ssh-agent -s
            sudo -E git pull origin master
  deploy-be:
    runs-on: ubuntu-latest
    needs: pull_code
    steps:
      - uses: actions/checkout@main
      - name: Run remote ssh commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          script_stop: true
          script: |
            cd /var/www/html/mycircle/backend
            sudo -E npm ci
            sudo -E pm2 stop backend || true
            sudo -E pm2 delete backend || true
            sudo -E pm2 start --name "backend" index.js
  deploy-fe:
    runs-on: ubuntu-latest
    needs: pull_code
    steps:
      - uses: actions/checkout@main
      - name: Run remote ssh commands
        uses: appleboy/ssh-action@v0.1.2
        with:
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.USERNAME }}
          script_stop: true
          script: |
            cd /var/www/html/mycircle/frontend
            sudo -E npm ci
            sudo -E npm run build
            cd server
            sudo -E npm ci
            sudo -E pm2 stop frontend || true
            sudo -E pm2 delete frontend || true
            sudo -E pm2 start --name "frontend" deploy.js
